### ISSUE TITLE
CI ToDo List

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/knut#3]
As mentioned in #1, apart from setting up the initial CI for testing, there's a few more ToDos:

- [x] enable cached builds
- [x] Add tests for mfc-utils and photonwidgets
- [x] Clazy check
- [x] pre-commit checks (including clang-format)
- [ ] clang-tidy check

Additional automations:
- [x] Release-please
- [x] Automatic documentation deployment?

**Comment by LeonMatthesKDAB** [comment]
This is mostly done now, and we don't want to enable clang-tidy at the moment, so let's close this issue :)
